name: tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    name: turbo run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm turbo run test
        env:
          NODE_ENV: test
      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: '**/coverage/**'
          if-no-files-found: ignore
          retention-days: 7
